version: "3.8"

services:
  django:
    container_name: web-app-container
    build:
      context: ./web-app
    command: >
      sh -c "python manage.py migrate &&
             python3 manage.py makemigrations &&
             ./startserver"
    ports:
      - 8000:8000
    volumes:
      - ./web-app:/app
    stdin_open: true
    tty: true
  react-native:
    container_name: mobile-app-container
    build:
      context: ./mobile-app
    ports:
      - 8081:8081
    volumes:
      - ./mobile-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
